"""create MEDISCOPE core schema

Revision ID: d3c3f62c6b75
Revises: 
Create Date: 2026-08-06 18:40:00.395457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c3f62c6b75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=80), nullable=False),
    sa.Column('evaluation_metrics', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'model_version', name='uq_model_version')
    )
    op.create_index(op.f('ix_model_registry_is_active'), 'model_registry', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_registry_model_name'), 'model_registry', ['model_name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('profile_picture_path', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('account_status', sa.String(length=60), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_status'), 'users', ['account_status'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_created', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_outcome'), 'audit_logs', ['outcome'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('linked_user_id', sa.Uuid(), nullable=True),
    sa.Column('synthetic_patient_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('lga', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('last_updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_user_id')
    )
    op.create_index(op.f('ix_patients_status'), 'patients', ['status'], unique=False)
    op.create_index(op.f('ix_patients_synthetic_patient_number'), 'patients', ['synthetic_patient_number'], unique=True)
    op.create_table('clinical_records',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('art_start_date', sa.Date(), nullable=True),
    sa.Column('age_at_art_initiation', sa.Float(), nullable=True),
    sa.Column('last_regimen', sa.String(length=200), nullable=True),
    sa.Column('days_of_arv_refill', sa.Float(), nullable=True),
    sa.Column('current_viral_load', sa.Float(), nullable=True),
    sa.Column('pregnancy_status', sa.String(length=100), nullable=True),
    sa.Column('last_clinic_visit_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_records_patient_id'), 'clinical_records', ['patient_id'], unique=False)
    op.create_table('clinician_patient_assignments',
    sa.Column('clinician_user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clinician_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinician_patient_assignments_clinician_user_id'), 'clinician_patient_assignments', ['clinician_user_id'], unique=False)
    op.create_index(op.f('ix_clinician_patient_assignments_is_active'), 'clinician_patient_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_clinician_patient_assignments_patient_id'), 'clinician_patient_assignments', ['patient_id'], unique=False)
    op.create_table('message_recipients',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'recipient_id', name='uq_message_recipient')
    )
    op.create_index(op.f('ix_message_recipients_message_id'), 'message_recipients', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_recipients_recipient_id'), 'message_recipients', ['recipient_id'], unique=False)
    op.create_table('predictions',
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('logistic_model_id', sa.Uuid(), nullable=False),
    sa.Column('xgboost_model_id', sa.Uuid(), nullable=False),
    sa.Column('logistic_probability', sa.Float(), nullable=False),
    sa.Column('logistic_classification', sa.String(length=50), nullable=False),
    sa.Column('xgboost_probability', sa.Float(), nullable=False),
    sa.Column('xgboost_classification', sa.String(length=50), nullable=False),
    sa.Column('agreement_status', sa.String(length=50), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('input_schema_version', sa.String(length=80), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clinical_review_status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['logistic_model_id'], ['model_registry.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['xgboost_model_id'], ['model_registry.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_generated_at'), 'predictions', ['generated_at'], unique=False)
    op.create_index('ix_predictions_patient_generated', 'predictions', ['patient_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_predictions_patient_id'), 'predictions', ['patient_id'], unique=False)
    op.create_table('health_record_change_requests',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('clinical_record_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=150), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_record_change_requests_patient_id'), 'health_record_change_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_health_record_change_requests_status'), 'health_record_change_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_record_change_requests_status'), table_name='health_record_change_requests')
    op.drop_index(op.f('ix_health_record_change_requests_patient_id'), table_name='health_record_change_requests')
    op.drop_table('health_record_change_requests')
    op.drop_index(op.f('ix_predictions_patient_id'), table_name='predictions')
    op.drop_index('ix_predictions_patient_generated', table_name='predictions')
    op.drop_index(op.f('ix_predictions_generated_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_message_recipients_recipient_id'), table_name='message_recipients')
    op.drop_index(op.f('ix_message_recipients_message_id'), table_name='message_recipients')
    op.drop_table('message_recipients')
    op.drop_index(op.f('ix_clinician_patient_assignments_patient_id'), table_name='clinician_patient_assignments')
    op.drop_index(op.f('ix_clinician_patient_assignments_is_active'), table_name='clinician_patient_assignments')
    op.drop_index(op.f('ix_clinician_patient_assignments_clinician_user_id'), table_name='clinician_patient_assignments')
    op.drop_table('clinician_patient_assignments')
    op.drop_index(op.f('ix_clinical_records_patient_id'), table_name='clinical_records')
    op.drop_table('clinical_records')
    op.drop_index(op.f('ix_patients_synthetic_patient_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_status'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_outcome'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_status'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_registry_model_name'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_is_active'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
