import { useState, type FormEvent, type ReactNode } from 'react';
import { ArrowLeft, ArrowRight, LockKeyhole } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { Brand } from '../components/Brand';
import { useAuth } from '../context/AuthContext';
import { api } from '../lib/api';

function AuthLayout({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
 return <div className="auth-page"><div className="auth-art"><Link to="/" className="back-link"><ArrowLeft size={16}/> Back home</Link><Brand/><div className="auth-art-copy"><span className="pill">Secure clinical workspace</span><h2>Human-centred intelligence for continuity of care.</h2><p>Protected by role-based access, MFA, audit logging and synthetic-data controls.</p></div></div><div className="auth-panel"><div className="auth-form-wrap"><h1>{title}</h1><p>{subtitle}</p>{children}</div></div></div>
}

export function LoginPage(){const {login,completeMfa}=useAuth();const nav=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [challenge,setChallenge]=useState('');const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{if(challenge){await completeMfa(challenge,code);nav('/app');}else{const r=await login(email,password);if(r.mfaRequired&&r.challengeToken)setChallenge(r.challengeToken);else nav('/app');}}catch(err){setError(err instanceof Error?err.message:'Unable to sign in.')}finally{setBusy(false)}}return <AuthLayout title={challenge?'Verify your identity':'Welcome back'} subtitle={challenge?'Enter the current code from your authenticator app.':'Sign in to your MEDISCOPE workspace.'}><form className="auth-form" onSubmit={submit}>{!challenge&&<><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="clinician@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="••••••••••••"/></label><div className="form-row"><label className="checkbox"><input type="checkbox"/> Remember this device</label><Link to="/forgot-password">Forgot password?</Link></div></>}{challenge&&<label>Authenticator code<input value={code} onChange={e=>setCode(e.target.value)} required maxLength={100} placeholder="6-digit code"/></label>}{error&&<div className="form-error">{error}</div>}<button className="button primary wide" disabled={busy}>{busy?'Please wait…':challenge?'Verify & continue':'Sign in'}<ArrowRight size={18}/></button></form>{!challenge&&<p className="auth-switch">New to MEDISCOPE? <Link to="/register">Create an account</Link></p>}</AuthLayout>}

export function RegisterPage(){const [done,setDone]=useState('');const [error,setError]=useState('');const [form,setForm]=useState({email:'',password:'',first_name:'',last_name:'',phone:'',gender:''});async function submit(e:FormEvent){e.preventDefault();try{const r=await api.register(form);setDone(r.message);setError('')}catch(err){setError(err instanceof Error?err.message:'Registration failed.')}}return <AuthLayout title="Create your account" subtitle="Register securely. Your email must be verified before activation."><form className="auth-form" onSubmit={submit}><div className="two-col"><label>First name<input required value={form.first_name} onChange={e=>setForm({...form,first_name:e.target.value})}/></label><label>Last name<input required value={form.last_name} onChange={e=>setForm({...form,last_name:e.target.value})}/></label></div><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input type="password" minLength={12} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="two-col"><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Gender<input value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}/></label></div>{error&&<div className="form-error">{error}</div>}{done&&<div className="form-success">{done}</div>}<button className="button primary wide">Create account <ArrowRight size={18}/></button></form><p className="auth-switch">Already registered? <Link to="/login">Sign in</Link></p></AuthLayout>}

export function VerifyEmailPage(){const [email,setEmail]=useState('');const [otp,setOtp]=useState('');const [message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();try{setMessage((await api.verifyEmail(email,otp)).message)}catch(err){setMessage(err instanceof Error?err.message:'Verification failed.')}}return <AuthLayout title="Verify your email" subtitle="Enter the six-digit verification code sent to your email."><form className="auth-form" onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Verification code<input required pattern="\d{6}" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value)}/></label>{message&&<div className="form-info">{message}</div>}<button className="button primary wide">Verify email</button></form></AuthLayout>}

export function ForgotPasswordPage(){const [email,setEmail]=useState('');const [message,setMessage]=useState('');async function submit(e:FormEvent){e.preventDefault();try{setMessage((await api.forgotPassword(email)).message)}catch(err){setMessage(err instanceof Error?err.message:'Request failed.')}}return <AuthLayout title="Reset your password" subtitle="We'll send reset instructions if the account is eligible."><form className="auth-form" onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{message&&<div className="form-info">{message}</div>}<button className="button primary wide"><LockKeyhole size={17}/> Send reset instructions</button></form></AuthLayout>}
